name: plumbers_toolkit
description: "An app to help plumbers in the field."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ^3.9.0

dependencies:
  awesome_flutter_extensions: ^2.0.1
  backdrop: ^0.9.1
  collection: ^1.19.1
  dart_mappable: ^4.6.0
  dartx: ^1.2.0
  extra_alignments: ^1.0.0+1
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_smart_dialog: ^4.9.8+9
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.0
  intl: any
  logging: ^1.3.0
  popover: ^0.3.1
  recase: ^4.1.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  tinycolor2: ^3.0.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
